### ISSUE TITLE
Freischaltung unseres Projektes auf der Travis-Plattform

### ISSUE THREAD

**Issue by baschte83** [ob-algdati-ws17/blatt-7-aufgabe-1-sbem#1]
Sehr geehrter Herr Braun,

unser Repository ist noch leer, trotzdem erbeten wir hiermit zur Vorbereitung unseres Projektes die Freischaltung unseres Projektes auf der Travis-Plattform.

Mit freundlichen Grüßen,
Ehsan Moslehi und Sebastian Baumann

**Comment by obcode** [comment]
https://travis-ci.org/ob-algdati-ws17/blatt-7-aufgabe-1-sbem
